export const jokes = [
  'How can you tell a Dogwood tree apart from other trees? By its bark.',
  'How come no one trusts atoms? Because they make up everything.',
  'How did one wave greet the other wave? She waved.',
  'How did the cell phone ask his girlfriend to marry him? He gave her a ring.',
  'How did the man like to watch fishing tournaments? Live stream.',
  'How did the puppies get across the lake? Doggie paddle.',
  'How do billboards talk to each other? Sign language.',
  'How do you fix a broken jack-o-lantern? With a pumpkin patch.',
  'How do you keep a bagel from running away? Put lox on it.',
  'How do you organize a party on Mars? You planet.',
  'How do you stop a bull from charging? Take away its credit cards. ',
  'How do you tell the difference between an alligator and a crocodile? One you will see later, the other after while.',
  'How many apples grow on trees? All of them.',
  'How much does a pirate pay to get his ears pierced? A buck an ear.',
  'What animal is always at a baseball game? A bat.',
  'What animal should you never trust to tell the truth? A lion.',
  'What awards do dentists receive? Plaques.',
  'What beans can you plant but never grow? Jelly beans.',
  'What body of water is the most detail oriented? The Pacific.',
  'What did the baby computer call his father? Data.',
  'What did the daddy buffalo say to his son when he left for camp? Bison.',
  'What did the duck say after he finished dinner? Put it on my bill.',
  'What did the janitor say when he jumped out of the work closet? Supplies!',
  'What did the lightbulb say to his girlfriend? I love you a watt.',
  'What do you call a snail on a ship? A snailor.',
  'What do you call someone with no body and no nose? Nobody knows. ',
  'What does a cow read every day? The moos-paper.',
  'What falls in winter but never gets hurt? Snow.',
  'What fish has the most fans? Starfish.',
  'What game do tornadoes play at parties? Twister.',
  'What instrument can you find in the bathroom? A tuba toothpaste.',
  'What is it called when a prisoner takes their own picture? A cell-fie.',
  'What is the easiest way to get a squirrel to like you? Act like a nut.',
  'What kind of cars do eggs drive? Yolkswaggons.',
  'What kind of dogs do magicians like? Labracadabradors',
  'What music do chiropractors listen to? Hip-pop.',
  'What shoes do bananas like to wear? Slippers.',
  'What type of tree can fit in your hand? Palm tree.',
  'What writing utensil does a boar use in class? A pig pen.',
  'When does a joke turn into a dad joke? When it becomes apparent.',
  'When is the best time to go to the dentist? Tooth-irty.',
  'Where do math teachers love to take vacations? Times Square.',
  'Where do pencils come from? Pennsylvania.',
  'Where do polar bears store their money? The snow bank.',
  'Where do sheep go on vacation? The Baaa-hamas.',
  'Where do walls meet after work? The corner.',
  'Which food tells the cheesiest jokes? Pizza.',
  'Which part of the body can you always count on? Your fingers. ',
  'Which season do people get injured the most? The fall.',
  'Which state has the most streets? Rhode Island.',
  'Which vegetable does a pirate never eat? Leeks.',
  'Who keeps the ocean floor clean? Mer-maids.',
  'Why are circles bad at telling stories? Because they are pointless.',
  'Why are ghosts bad liars? You can see right through them.',
  'Why are oranges so slow? They always run out of juice.',
  'Why are pirates bad at singing the alphabet song? They get stuck at C.',
  'Why are shrimp bad at sharing? They are shellfish.',
  'Why are volcanoes so popular? They are lava-able.',
  'Why did the coach run to the bank in such a hurry? To get his quarterback.',
  'Why did the computer go to the doctor? It had a virus.',
  'Why did the cookie go to the hospital? He felt crumby.',
  'Why did the family sell their vacuum cleaner? It was collecting dust.',
  'Why did the kids cross the playground? To get to the other slides.',
  'Why did the man run around the bed? He was trying to catch up on his sleep.',
  'Why did the student eat his homework? The teacher said it was a piece of cake.',
  'Why did the tomato blush? Because it saw salad dressing.',
  'Why do dads tell such corny jokes? They want you to groan up.',
  'Why do frogs never park illegally? They are afraid of getting toad.',
  'Why do golfers always pack an extra pair of pants? In case they get a hole in one.',
  'Why do melons have weddings? Because they cantaloupe.',
  'Why do spiders know everything? They get their information from the Web.',
  'Why should you never play hide and seek with a leopard? They are always spotted.',
  'Why was 6 afraid of 7? Because 7,8,9.',
  'Why was the broom late for school? It over-swept.',
  'Why was the man afraid of the calendar? Its days were numbered.',
  'Why was the math book crying? It had lots of problems.',
  "How can you tell when a vampire is sick? He's coffin a lot.",
  "What did one candy bar say to the other candy bar? I've got some Twix up my sleeve.",
  "What did the apple say to the kangaroo? Nothing.Apples can't talk.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "What has hands but can't clap? A clock.",
  "What is a lazy person's favorite shoes to wear? Loafers.",
  "What is a witch's favorite subject in school? Spelling.",
  "What kind of lion doesn't roar? A dandelion.",
  "What's a knight's favorite dish? Swordfish",
  "What's a moth's favorite stroke? The butterfly.",
  "Where is a fruit's favorite place to go on vacation? Pear-is!",
  "Where's the best place to learn to make a banana split? Sundae school.",
  "Who was the fattest knight at King Arthur's round table? Sir Cumference.",
  "Why can't a nose be 12 inches long? Because then it would be a foot.",
  "Why can't Monday lift Saturday? It is a weak day.",
  "Why couldn't the hamburger go into the bar? It didn't serve food.",
  "Why couldn't the pony sing at the talent show? She was a little horse. ",
  "Why didn't the bicycle stand up? It was two tired.",
  "Why didn't the lady trust the stairs? She thought they were up to something.",
  "Why didn't the man iron his four-leaf clover? He didn't want to press his luck.",
  "Why didn't the teddy bear come down for dinner? He was already stuffed.",
  "Why don't dogs like walking in the rain? They are afraid of Poodles.",
  "Why don't pirates take a bath? They prefer to wash up on shore.",
  "Why shouldn't you marry a tennis player? Because love means nothing to them.",
]

export const getRandomJoke = () => {
  const randomIndex = Math.floor(Math.random() * (jokes.length - 1 - 0 + 1) + 0)
  return jokes[randomIndex]
}
