name: Jest tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v2.3.3

      - name: Setup Node 14
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14

      - name: Install dependancies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Run jest tests
        run: yarn test
